import { Link } from "react-router-dom";

export default function Privacy() {
  return (
    <section className="mx-auto max-w-2xl space-y-8 px-4 py-12">
      <header className="space-y-2">
        <Link to="/auth" className="text-xs font-medium text-sage hover:underline">
          ← Back
        </Link>
        <h1 className="text-3xl font-semibold text-ink">Privacy Policy</h1>
        <p className="text-sm text-ink/50">Last updated: June 2026</p>
      </header>

      <div className="space-y-6 text-sm leading-relaxed text-ink/80">
        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">1. About Ra7etBal</h2>
          <p>
            Ra7etBal ("we", "our", or "the app") is a personal mental load assistant that helps
            you capture tasks, reminders, delegations, and calendar events — and lets you interact
            with them using your voice through Carson, your AI Chief of Staff.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">2. What We Collect</h2>
          <p>We collect only what is necessary to provide the service:</p>
          <ul className="ml-4 list-disc space-y-1">
            <li>Your email address and display name, used to create and identify your account.</li>
            <li>Tasks, notes, reminders, and delegations you create inside the app.</li>
            <li>
              Voice session summaries generated by Carson, stored to give Carson memory across
              sessions.
            </li>
            <li>
              Google Calendar access tokens, stored securely server-side and never shared. Used
              only to read and manage calendar events on your behalf when you connect Google
              Calendar.
            </li>
            <li>
              Your preferred weather city and timezone, used to personalise your daily brief.
            </li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">3. Google Calendar</h2>
          <p>
            If you choose to connect Google Calendar, Ra7etBal requests access to read and manage
            events on your primary calendar. This access is used exclusively to show your upcoming
            events to Carson and to create, update, or delete calendar events at your instruction.
          </p>
          <p>
            We store a Google refresh token server-side so we can access your calendar on your
            behalf. This token is never exposed to the browser or shared with any third party.
          </p>
          <p>
            You can disconnect Google Calendar at any time from the Settings screen inside the
            app. Disconnecting immediately removes your stored token from our database.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">4. How We Use Your Data</h2>
          <p>Your data is used solely to operate the Ra7etBal service for you:</p>
          <ul className="ml-4 list-disc space-y-1">
            <li>To power Carson's voice assistant and memory.</li>
            <li>To send delegations and reminders via WhatsApp on your behalf.</li>
            <li>To deliver your daily operating brief.</li>
            <li>To send push notifications for reminders and escalations.</li>
          </ul>
          <p>We do not use your data for advertising, profiling, or any other purpose.</p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">5. We Do Not Sell Your Data</h2>
          <p>
            We do not sell, rent, or share your personal data with any third party for commercial
            purposes. We will never sell your data.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">6. Data Storage and Security</h2>
          <p>
            Your data is stored in Supabase, a secure cloud database. All data is encrypted in
            transit (HTTPS) and at rest. Access is protected by row-level security policies so
            your data is only accessible to your account.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">7. Data Deletion</h2>
          <p>
            You can request deletion of your account and all associated data at any time by
            contacting us at{" "}
            <a href="mailto:support@ra7etbal.com" className="text-sage hover:underline">
              support@ra7etbal.com
            </a>
            . We will delete your data within 30 days of your request.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">8. Third-Party Services</h2>
          <p>Ra7etBal uses the following third-party services to operate:</p>
          <ul className="ml-4 list-disc space-y-1">
            <li>Supabase — database and authentication</li>
            <li>ElevenLabs — voice AI</li>
            <li>Anthropic — AI text processing</li>
            <li>Google Calendar API — calendar access (only when you connect)</li>
            <li>Meta WhatsApp Cloud API — sending delegations and reminders</li>
            <li>Vercel — hosting</li>
          </ul>
          <p>Each of these services has its own privacy policy governing how they handle data.</p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-semibold text-ink">9. Contact</h2>
          <p>
            For any privacy questions or data requests, contact us at{" "}
            <a href="mailto:support@ra7etbal.com" className="text-sage hover:underline">
              support@ra7etbal.com
            </a>
            .
          </p>
        </section>
      </div>
    </section>
  );
}
